/**
 * Comprehensive IANA timezone list grouped by region.
 * Used for timezone dropdown selectors across the dashboard.
 */

export const TIMEZONE_GROUPS = {
  'US & Canada': [
    'America/New_York',
    'America/Chicago',
    'America/Denver',
    'America/Los_Angeles',
    'America/Anchorage',
    'Pacific/Honolulu',
    'America/Phoenix',
    'America/Indiana/Indianapolis',
    'America/Detroit',
    'America/Kentucky/Louisville',
    'America/Boise',
    'America/Juneau',
    'America/Adak',
    'America/Nome',
    'America/Sitka',
    'America/Yakutat',
    'America/Metlakatla',
    'America/Menominee',
    'America/North_Dakota/Center',
    'America/North_Dakota/New_Salem',
    'America/North_Dakota/Beulah',
    'America/Indiana/Knox',
    'America/Indiana/Marengo',
    'America/Indiana/Petersburg',
    'America/Indiana/Tell_City',
    'America/Indiana/Vevay',
    'America/Indiana/Vincennes',
    'America/Indiana/Winamac',
    'America/Kentucky/Monticello',
    'America/Toronto',
    'America/Vancouver',
    'America/Winnipeg',
    'America/Edmonton',
    'America/Halifax',
    'America/Regina',
    'America/St_Johns',
    'America/Yellowknife',
    'America/Whitehorse',
    'America/Iqaluit',
    'America/Moncton',
    'America/Thunder_Bay',
  ],
  'Central & South America': [
    'America/Mexico_City',
    'America/Cancun',
    'America/Tijuana',
    'America/Bogota',
    'America/Lima',
    'America/Santiago',
    'America/Buenos_Aires',
    'America/Sao_Paulo',
    'America/Caracas',
    'America/Guatemala',
    'America/Havana',
    'America/Jamaica',
    'America/Panama',
    'America/Costa_Rica',
    'America/El_Salvador',
    'America/Tegucigalpa',
    'America/Managua',
    'America/Guayaquil',
    'America/La_Paz',
    'America/Asuncion',
    'America/Montevideo',
    'America/Guyana',
    'America/Paramaribo',
    'America/Port-au-Prince',
    'America/Santo_Domingo',
    'America/Puerto_Rico',
    'America/Martinique',
    'America/Barbados',
    'America/Curacao',
    'America/Aruba',
    'America/Trinidad',
    'America/Cayenne',
    'America/Belize',
    'America/Recife',
    'America/Fortaleza',
    'America/Manaus',
    'America/Belem',
    'America/Cuiaba',
    'America/Campo_Grande',
    'America/Porto_Velho',
    'America/Rio_Branco',
    'America/Noronha',
    'America/Araguaina',
    'America/Bahia',
    'America/Maceio',
    'America/Cordoba',
    'America/Mendoza',
    'America/Punta_Arenas',
  ],
  'Europe': [
    'UTC',
    'Europe/London',
    'Europe/Dublin',
    'Europe/Lisbon',
    'Europe/Paris',
    'Europe/Berlin',
    'Europe/Amsterdam',
    'Europe/Brussels',
    'Europe/Zurich',
    'Europe/Vienna',
    'Europe/Rome',
    'Europe/Madrid',
    'Europe/Barcelona',
    'Europe/Stockholm',
    'Europe/Oslo',
    'Europe/Copenhagen',
    'Europe/Helsinki',
    'Europe/Warsaw',
    'Europe/Prague',
    'Europe/Budapest',
    'Europe/Bucharest',
    'Europe/Sofia',
    'Europe/Athens',
    'Europe/Istanbul',
    'Europe/Moscow',
    'Europe/Kiev',
    'Europe/Minsk',
    'Europe/Riga',
    'Europe/Tallinn',
    'Europe/Vilnius',
    'Europe/Belgrade',
    'Europe/Zagreb',
    'Europe/Ljubljana',
    'Europe/Sarajevo',
    'Europe/Skopje',
    'Europe/Bratislava',
    'Europe/Luxembourg',
    'Europe/Malta',
    'Europe/Monaco',
    'Europe/Andorra',
    'Europe/Gibraltar',
    'Europe/Tirane',
    'Europe/Chisinau',
    'Europe/Samara',
    'Europe/Volgograd',
    'Europe/Kaliningrad',
    'Atlantic/Reykjavik',
    'Atlantic/Azores',
    'Atlantic/Canary',
    'Atlantic/Faroe',
    'Atlantic/Madeira',
  ],
  'Africa': [
    'Africa/Cairo',
    'Africa/Lagos',
    'Africa/Nairobi',
    'Africa/Johannesburg',
    'Africa/Casablanca',
    'Africa/Accra',
    'Africa/Algiers',
    'Africa/Tunis',
    'Africa/Tripoli',
    'Africa/Khartoum',
    'Africa/Addis_Ababa',
    'Africa/Dar_es_Salaam',
    'Africa/Kampala',
    'Africa/Maputo',
    'Africa/Lusaka',
    'Africa/Harare',
    'Africa/Windhoek',
    'Africa/Luanda',
    'Africa/Kinshasa',
    'Africa/Lubumbashi',
    'Africa/Douala',
    'Africa/Libreville',
    'Africa/Brazzaville',
    'Africa/Malabo',
    'Africa/Niamey',
    'Africa/Ndjamena',
    'Africa/Bamako',
    'Africa/Nouakchott',
    'Africa/Dakar',
    'Africa/Conakry',
    'Africa/Freetown',
    'Africa/Monrovia',
    'Africa/Abidjan',
    'Africa/Lome',
    'Africa/Porto-Novo',
    'Africa/Ouagadougou',
    'Africa/Banjul',
    'Africa/Bissau',
    'Africa/Sao_Tome',
    'Africa/Asmara',
    'Africa/Djibouti',
    'Africa/Mogadishu',
    'Africa/Juba',
    'Africa/Kigali',
    'Africa/Bujumbura',
    'Africa/Blantyre',
    'Africa/Gaborone',
    'Africa/Maseru',
    'Africa/Mbabane',
    'Indian/Antananarivo',
    'Indian/Mauritius',
    'Indian/Reunion',
    'Indian/Mayotte',
    'Indian/Comoro',
    'Atlantic/Cape_Verde',
  ],
  'Asia': [
    'Asia/Dubai',
    'Asia/Riyadh',
    'Asia/Qatar',
    'Asia/Kuwait',
    'Asia/Bahrain',
    'Asia/Muscat',
    'Asia/Tehran',
    'Asia/Baghdad',
    'Asia/Amman',
    'Asia/Beirut',
    'Asia/Damascus',
    'Asia/Jerusalem',
    'Asia/Karachi',
    'Asia/Kolkata',
    'Asia/Colombo',
    'Asia/Dhaka',
    'Asia/Kathmandu',
    'Asia/Almaty',
    'Asia/Tashkent',
    'Asia/Bishkek',
    'Asia/Tbilisi',
    'Asia/Baku',
    'Asia/Yerevan',
    'Asia/Kabul',
    'Asia/Ashgabat',
    'Asia/Dushanbe',
    'Asia/Rangoon',
    'Asia/Bangkok',
    'Asia/Jakarta',
    'Asia/Ho_Chi_Minh',
    'Asia/Phnom_Penh',
    'Asia/Vientiane',
    'Asia/Singapore',
    'Asia/Kuala_Lumpur',
    'Asia/Brunei',
    'Asia/Manila',
    'Asia/Shanghai',
    'Asia/Hong_Kong',
    'Asia/Macau',
    'Asia/Taipei',
    'Asia/Seoul',
    'Asia/Tokyo',
    'Asia/Pyongyang',
    'Asia/Ulaanbaatar',
    'Asia/Vladivostok',
    'Asia/Irkutsk',
    'Asia/Krasnoyarsk',
    'Asia/Novosibirsk',
    'Asia/Omsk',
    'Asia/Yekaterinburg',
    'Asia/Magadan',
    'Asia/Kamchatka',
    'Asia/Sakhalin',
    'Asia/Yakutsk',
    'Asia/Chita',
    'Asia/Srednekolymsk',
    'Asia/Anadyr',
  ],
  'Australia & Pacific': [
    'Australia/Sydney',
    'Australia/Melbourne',
    'Australia/Brisbane',
    'Australia/Perth',
    'Australia/Adelaide',
    'Australia/Hobart',
    'Australia/Darwin',
    'Australia/Lord_Howe',
    'Pacific/Auckland',
    'Pacific/Fiji',
    'Pacific/Chatham',
    'Pacific/Tongatapu',
    'Pacific/Apia',
    'Pacific/Noumea',
    'Pacific/Port_Moresby',
    'Pacific/Guadalcanal',
    'Pacific/Efate',
    'Pacific/Tarawa',
    'Pacific/Majuro',
    'Pacific/Kwajalein',
    'Pacific/Pago_Pago',
    'Pacific/Guam',
    'Pacific/Palau',
    'Pacific/Kosrae',
    'Pacific/Pohnpei',
    'Pacific/Chuuk',
    'Pacific/Wake',
    'Pacific/Midway',
    'Pacific/Gambier',
    'Pacific/Marquesas',
    'Pacific/Tahiti',
    'Pacific/Pitcairn',
    'Pacific/Easter',
    'Pacific/Galapagos',
    'Pacific/Rarotonga',
    'Pacific/Niue',
    'Pacific/Norfolk',
    'Indian/Maldives',
    'Indian/Chagos',
    'Indian/Cocos',
    'Indian/Christmas',
  ],
};

/**
 * Flat list of all timezones for simple iteration.
 */
export const ALL_TIMEZONES = Object.values(TIMEZONE_GROUPS).flat();

/**
 * Get a human-friendly label for a timezone.
 * e.g. "America/New_York" → "America/New York (EST)"
 */
export function getTimezoneLabel(tz) {
  try {
    const now = new Date();
    const formatter = new Intl.DateTimeFormat('en-US', { timeZone: tz, timeZoneName: 'short' });
    const parts = formatter.formatToParts(now);
    const abbr = parts.find(p => p.type === 'timeZoneName')?.value || '';
    const display = tz.replace(/_/g, ' ');
    return abbr ? `${display} (${abbr})` : display;
  } catch {
    return tz.replace(/_/g, ' ');
  }
}

/**
 * Render a timezone <select> using Preact's h().
 * @param {Function} h - Preact createElement
 * @param {string} value - Current selected timezone
 * @param {Function} onChange - Change handler (receives event)
 * @param {object} [props] - Additional props for the <select> element
 */
export function TimezoneSelect(h, value, onChange, props = {}) {
  return h('select', { className: 'input', value, onChange, ...props },
    h('option', { value: '' }, '-- Select Timezone --'),
    Object.entries(TIMEZONE_GROUPS).map(([group, tzs]) =>
      h('optgroup', { key: group, label: group },
        tzs.map(tz => h('option', { key: tz, value: tz }, getTimezoneLabel(tz)))
      )
    )
  );
}
