export const DEFAULT_AGENTICMAIL_BROWSER_ENABLED = true;
export const DEFAULT_BROWSER_EVALUATE_ENABLED = true;
export const DEFAULT_AGENTICMAIL_BROWSER_COLOR = "#E91E8C";
export const DEFAULT_AGENTICMAIL_BROWSER_PROFILE_NAME = "AgenticMail";
export const DEFAULT_BROWSER_DEFAULT_PROFILE_NAME = "chrome";
export const DEFAULT_AI_SNAPSHOT_MAX_CHARS = 16_000;
export const DEFAULT_AI_SNAPSHOT_EFFICIENT_MAX_CHARS = 10_000;
export const DEFAULT_AI_SNAPSHOT_EFFICIENT_DEPTH = 6;
