/**
 * Integration Catalog — Auto-generated from MCP adapters.
 * Single source of truth for all 3rd-party integrations.
 * Used by dashboard Integrations tab and MCP bridge credential resolution.
 */

export interface IntegrationEntry {
  skillId: string;
  name: string;
  authType: "oauth2" | "api_key" | "token" | "credentials";
  category: string;
  toolCount: number;
  /** For credentials type: required field names */
  fields?: string[];
}

export const INTEGRATION_CATALOG: IntegrationEntry[] = [
  { skillId: "activecampaign", name: "ActiveCampaign", authType: "api_key", category: "marketing", toolCount: 5 },
  { skillId: "adobe-sign", name: "Adobe Acrobat Sign", authType: "oauth2", category: "design", toolCount: 5 },
  { skillId: "adp", name: "ADP Workforce", authType: "oauth2", category: "hr", toolCount: 5 },
  { skillId: "airtable-bases", name: "Airtable", authType: "oauth2", category: "productivity", toolCount: 3 },
  { skillId: "apollo-io", name: "Apollo.io Sales Intelligence", authType: "api_key", category: "crm", toolCount: 5 },
  { skillId: "asana-tasks", name: "Asana", authType: "oauth2", category: "productivity", toolCount: 4 },
  { skillId: "auth0", name: "Auth0", authType: "token", category: "security", toolCount: 5 },
  { skillId: "aws-services", name: "AWS Services", authType: "credentials", category: "infrastructure", toolCount: 3 },
  { skillId: "azure-devops", name: "Azure DevOps", authType: "token", category: "devops", toolCount: 5 },
  { skillId: "bamboohr", name: "BambooHR", authType: "api_key", category: "hr", toolCount: 5 },
  { skillId: "basecamp", name: "Basecamp", authType: "oauth2", category: "productivity", toolCount: 5 },
  { skillId: "bigcommerce", name: "BigCommerce", authType: "api_key", category: "ecommerce", toolCount: 5 },
  { skillId: "bitbucket-repos", name: "Bitbucket", authType: "oauth2", category: "devops", toolCount: 3 },
  { skillId: "box", name: "Box", authType: "oauth2", category: "design", toolCount: 5 },
  { skillId: "brex", name: "Brex", authType: "token", category: "finance", toolCount: 5 },
  { skillId: "buffer", name: "Buffer Social Media", authType: "oauth2", category: "marketing", toolCount: 5 },
  { skillId: "calendly", name: "Calendly", authType: "token", category: "communication", toolCount: 4 },
  { skillId: "canva-design", name: "Canva", authType: "oauth2", category: "design", toolCount: 3 },
  { skillId: "chargebee", name: "Chargebee", authType: "api_key", category: "finance", toolCount: 5 },
  { skillId: "circleci-pipelines", name: "CircleCI", authType: "token", category: "devops", toolCount: 3 },
  { skillId: "clickup", name: "ClickUp", authType: "token", category: "productivity", toolCount: 5 },
  { skillId: "close-crm", name: "Close CRM", authType: "api_key", category: "crm", toolCount: 5 },
  { skillId: "cloudflare-cdn", name: "Cloudflare", authType: "token", category: "infrastructure", toolCount: 4 },
  { skillId: "confluence-wiki", name: "Confluence", authType: "oauth2", category: "productivity", toolCount: 3 },
  { skillId: "contentful", name: "Contentful CMS", authType: "token", category: "marketing", toolCount: 5 },
  { skillId: "copper-crm", name: "Copper CRM", authType: "api_key", category: "crm", toolCount: 5 },
  { skillId: "crisp", name: "Crisp Chat", authType: "credentials", category: "communication", toolCount: 5 },
  { skillId: "crowdstrike", name: "CrowdStrike", authType: "oauth2", category: "security", toolCount: 5 },
  { skillId: "datadog-monitoring", name: "Datadog", authType: "credentials", category: "monitoring", toolCount: 4 },
  { skillId: "digitalocean", name: "DigitalOcean", authType: "token", category: "infrastructure", toolCount: 5 },
  { skillId: "discord", name: "Discord", authType: "token", category: "communication", toolCount: 4 },
  { skillId: "docker-containers", name: "Docker Hub", authType: "token", category: "devops", toolCount: 3 },
  { skillId: "docusign-esign", name: "DocuSign", authType: "oauth2", category: "finance", toolCount: 3 },
  { skillId: "drift", name: "Drift Conversational Marketing", authType: "oauth2", category: "communication", toolCount: 5 },
  { skillId: "dropbox-storage", name: "Dropbox", authType: "oauth2", category: "productivity", toolCount: 4 },
  { skillId: "figma-design", name: "Figma", authType: "oauth2", category: "design", toolCount: 4 },
  { skillId: "firebase", name: "Firebase", authType: "oauth2", category: "data-ai", toolCount: 5 },
  { skillId: "flyio", name: "Fly.io", authType: "token", category: "infrastructure", toolCount: 5 },
  { skillId: "freshbooks", name: "FreshBooks", authType: "oauth2", category: "finance", toolCount: 5 },
  { skillId: "freshdesk", name: "Freshdesk Support", authType: "api_key", category: "crm", toolCount: 5 },
  { skillId: "freshsales", name: "Freshsales CRM", authType: "api_key", category: "crm", toolCount: 5 },
  { skillId: "freshservice", name: "Freshservice ITSM", authType: "api_key", category: "general", toolCount: 5 },
  { skillId: "front", name: "Front", authType: "token", category: "communication", toolCount: 5 },
  { skillId: "github-actions", name: "GitHub Actions", authType: "oauth2", category: "devops", toolCount: 4 },
  { skillId: "github", name: "GitHub", authType: "oauth2", category: "devops", toolCount: 5 },
  { skillId: "gitlab-ci", name: "GitLab", authType: "oauth2", category: "devops", toolCount: 5 },
  { skillId: "gong", name: "Gong Revenue Intelligence", authType: "token", category: "crm", toolCount: 5 },
  { skillId: "google-ads", name: "Google Ads", authType: "oauth2", category: "marketing", toolCount: 3 },
  { skillId: "google-analytics", name: "Google Analytics", authType: "oauth2", category: "monitoring", toolCount: 3 },
  { skillId: "google-cloud", name: "Google Cloud Platform", authType: "oauth2", category: "infrastructure", toolCount: 3 },
  { skillId: "gotomeeting", name: "GoTo Meeting", authType: "oauth2", category: "communication", toolCount: 4 },
  { skillId: "grafana", name: "Grafana", authType: "api_key", category: "monitoring", toolCount: 5 },
  { skillId: "greenhouse", name: "Greenhouse Recruiting", authType: "api_key", category: "hr", toolCount: 5 },
  { skillId: "gusto", name: "Gusto Payroll", authType: "oauth2", category: "hr", toolCount: 5 },
  { skillId: "hashicorp-vault", name: "HashiCorp Vault", authType: "api_key", category: "infrastructure", toolCount: 5 },
  { skillId: "heroku", name: "Heroku", authType: "token", category: "infrastructure", toolCount: 5 },
  { skillId: "hibob", name: "HiBob", authType: "token", category: "hr", toolCount: 5 },
  { skillId: "hootsuite", name: "Hootsuite", authType: "oauth2", category: "marketing", toolCount: 5 },
  { skillId: "hubspot-crm", name: "HubSpot CRM", authType: "oauth2", category: "crm", toolCount: 5 },
  { skillId: "huggingface", name: "HuggingFace", authType: "token", category: "data-ai", toolCount: 5 },
  { skillId: "intercom-support", name: "Intercom Support", authType: "oauth2", category: "communication", toolCount: 3 },
  { skillId: "jira", name: "Jira", authType: "oauth2", category: "general", toolCount: 5 },
  { skillId: "klaviyo", name: "Klaviyo", authType: "api_key", category: "marketing", toolCount: 5 },
  { skillId: "kubernetes-cluster", name: "Kubernetes", authType: "token", category: "infrastructure", toolCount: 4 },
  { skillId: "lattice", name: "Lattice Performance", authType: "api_key", category: "hr", toolCount: 5 },
  { skillId: "launchdarkly", name: "LaunchDarkly", authType: "api_key", category: "devops", toolCount: 5 },
  { skillId: "lever", name: "Lever Recruiting", authType: "oauth2", category: "hr", toolCount: 5 },
  { skillId: "linear", name: "Linear", authType: "oauth2", category: "general", toolCount: 3 },
  { skillId: "linkedin", name: "LinkedIn", authType: "oauth2", category: "social", toolCount: 5 },
  { skillId: "livechat", name: "LiveChat", authType: "token", category: "communication", toolCount: 4 },
  { skillId: "loom-video", name: "Loom", authType: "token", category: "communication", toolCount: 4 },
  { skillId: "mailchimp-campaigns", name: "Mailchimp", authType: "oauth2", category: "communication", toolCount: 4 },
  { skillId: "mailgun", name: "Mailgun", authType: "api_key", category: "communication", toolCount: 5 },
  { skillId: "miro-boards", name: "Miro", authType: "oauth2", category: "communication", toolCount: 4 },
  { skillId: "mixpanel-analytics", name: "Mixpanel", authType: "credentials", category: "monitoring", toolCount: 3 },
  { skillId: "monday-boards", name: "Monday.com", authType: "oauth2", category: "productivity", toolCount: 3 },
  { skillId: "mongodb-atlas", name: "MongoDB Atlas", authType: "credentials", category: "data-ai", toolCount: 5 },
  { skillId: "neon", name: "Neon Serverless Postgres", authType: "api_key", category: "data-ai", toolCount: 5 },
  { skillId: "netlify", name: "Netlify", authType: "token", category: "infrastructure", toolCount: 5 },
  { skillId: "netsuite", name: "NetSuite ERP", authType: "oauth2", category: "finance", toolCount: 5 },
  { skillId: "newrelic", name: "New Relic", authType: "api_key", category: "monitoring", toolCount: 5 },
  { skillId: "notion", name: "Notion", authType: "oauth2", category: "productivity", toolCount: 3 },
  { skillId: "okta", name: "Okta Identity", authType: "api_key", category: "security", toolCount: 5 },
  { skillId: "openai", name: "OpenAI", authType: "api_key", category: "data-ai", toolCount: 5 },
  { skillId: "opsgenie", name: "OpsGenie", authType: "api_key", category: "monitoring", toolCount: 5 },
  { skillId: "outreach", name: "Outreach Sales Engagement", authType: "oauth2", category: "crm", toolCount: 5 },
  { skillId: "paddle", name: "Paddle", authType: "api_key", category: "finance", toolCount: 5 },
  { skillId: "pagerduty", name: "PagerDuty", authType: "api_key", category: "monitoring", toolCount: 5 },
  { skillId: "pandadoc", name: "PandaDoc", authType: "api_key", category: "design", toolCount: 5 },
  { skillId: "paypal", name: "PayPal", authType: "oauth2", category: "finance", toolCount: 5 },
  { skillId: "personio", name: "Personio", authType: "token", category: "hr", toolCount: 5 },
  { skillId: "pinecone", name: "Pinecone", authType: "api_key", category: "data-ai", toolCount: 5 },
  { skillId: "pipedrive-deals", name: "Pipedrive Deals", authType: "api_key", category: "crm", toolCount: 3 },
  { skillId: "plaid", name: "Plaid", authType: "api_key", category: "finance", toolCount: 5 },
  { skillId: "postmark", name: "Postmark", authType: "api_key", category: "communication", toolCount: 5 },
  { skillId: "power-automate", name: "Microsoft Power Automate", authType: "oauth2", category: "enterprise", toolCount: 5 },
  { skillId: "quickbooks-accounting", name: "QuickBooks", authType: "oauth2", category: "finance", toolCount: 4 },
  { skillId: "recurly", name: "Recurly", authType: "api_key", category: "finance", toolCount: 5 },
  { skillId: "reddit", name: "Reddit", authType: "oauth2", category: "social", toolCount: 5 },
  { skillId: "render", name: "Render", authType: "api_key", category: "infrastructure", toolCount: 5 },
  { skillId: "ringcentral", name: "RingCentral", authType: "oauth2", category: "communication", toolCount: 4 },
  { skillId: "rippling", name: "Rippling HR", authType: "token", category: "hr", toolCount: 5 },
  { skillId: "salesforce", name: "Salesforce", authType: "oauth2", category: "crm", toolCount: 5 },
  { skillId: "salesloft", name: "SalesLoft", authType: "oauth2", category: "crm", toolCount: 5 },
  { skillId: "sanity", name: "Sanity CMS", authType: "token", category: "marketing", toolCount: 5 },
  { skillId: "sap", name: "SAP S/4HANA", authType: "oauth2", category: "enterprise", toolCount: 5 },
  { skillId: "segment-cdp", name: "Segment", authType: "token", category: "monitoring", toolCount: 3 },
  { skillId: "sendgrid-email", name: "SendGrid Email", authType: "api_key", category: "communication", toolCount: 3 },
  { skillId: "sentry", name: "Sentry Error Tracking", authType: "token", category: "monitoring", toolCount: 5 },
  { skillId: "servicenow", name: "ServiceNow", authType: "oauth2", category: "enterprise", toolCount: 5 },
  { skillId: "shopify", name: "Shopify", authType: "api_key", category: "ecommerce", toolCount: 5 },
  { skillId: "shortcut", name: "Shortcut", authType: "api_key", category: "productivity", toolCount: 5 },
  { skillId: "slack", name: "Slack", authType: "oauth2", category: "communication", toolCount: 6 },
  { skillId: "smartsheet", name: "Smartsheet", authType: "token", category: "productivity", toolCount: 5 },
  { skillId: "snowflake-warehouse", name: "Snowflake", authType: "credentials", category: "infrastructure", toolCount: 4 },
  { skillId: "snyk", name: "Snyk Security", authType: "api_key", category: "security", toolCount: 5 },
  { skillId: "splunk", name: "Splunk", authType: "token", category: "monitoring", toolCount: 5 },
  { skillId: "square", name: "Square", authType: "oauth2", category: "finance", toolCount: 5 },
  { skillId: "statuspage", name: "Atlassian Statuspage", authType: "api_key", category: "monitoring", toolCount: 5 },
  { skillId: "stripe", name: "Stripe", authType: "api_key", category: "finance", toolCount: 5 },
  { skillId: "supabase", name: "Supabase", authType: "api_key", category: "data-ai", toolCount: 5 },
  { skillId: "teamwork", name: "Teamwork", authType: "token", category: "productivity", toolCount: 5 },
  { skillId: "telegram-bot", name: "Telegram Bot", authType: "api_key", category: "communication", toolCount: 4 },
  { skillId: "terraform-iac", name: "Terraform Cloud", authType: "token", category: "infrastructure", toolCount: 3 },
  { skillId: "todoist-tasks", name: "Todoist", authType: "oauth2", category: "productivity", toolCount: 4 },
  { skillId: "trello-cards", name: "Trello", authType: "credentials", category: "productivity", toolCount: 4 },
  { skillId: "twilio-sms", name: "Twilio SMS", authType: "credentials", category: "communication", toolCount: 3 },
  { skillId: "twitter", name: "Twitter/X", authType: "oauth2", category: "social", toolCount: 5 },
  { skillId: "vercel-deployments", name: "Vercel", authType: "oauth2", category: "devops", toolCount: 3 },
  { skillId: "weaviate", name: "Weaviate", authType: "api_key", category: "data-ai", toolCount: 5 },
  { skillId: "webex", name: "Webex", authType: "oauth2", category: "communication", toolCount: 4 },
  { skillId: "webflow", name: "Webflow", authType: "oauth2", category: "marketing", toolCount: 5 },
  { skillId: "whatsapp-business", name: "WhatsApp Business", authType: "token", category: "communication", toolCount: 4 },
  { skillId: "whereby", name: "Whereby", authType: "api_key", category: "communication", toolCount: 4 },
  { skillId: "woocommerce", name: "WooCommerce", authType: "credentials", category: "ecommerce", toolCount: 5 },
  { skillId: "wordpress", name: "WordPress", authType: "token", category: "cms", toolCount: 5 },
  { skillId: "workday", name: "Workday", authType: "oauth2", category: "hr", toolCount: 5 },
  { skillId: "wrike", name: "Wrike", authType: "oauth2", category: "productivity", toolCount: 5 },
  { skillId: "xero", name: "Xero Accounting", authType: "oauth2", category: "finance", toolCount: 5 },
  { skillId: "youtube", name: "YouTube", authType: "oauth2", category: "social", toolCount: 5 },
  { skillId: "zendesk-tickets", name: "Zendesk Tickets", authType: "oauth2", category: "crm", toolCount: 4 },
  { skillId: "zoho-crm", name: "Zoho CRM", authType: "oauth2", category: "crm", toolCount: 6 },
  { skillId: "zoom-meetings", name: "Zoom Meetings", authType: "oauth2", category: "communication", toolCount: 3 },
  { skillId: "zuora", name: "Zuora", authType: "oauth2", category: "finance", toolCount: 5 },
];

export const INTEGRATION_MAP = new Map(INTEGRATION_CATALOG.map(e => [e.skillId, e]));

/** Get all integrations in a category */
export function getIntegrationsByCategory(category: string): IntegrationEntry[] {
  return INTEGRATION_CATALOG.filter(e => e.category === category);
}

/** All unique categories */
export const INTEGRATION_CATEGORIES = [...new Set(INTEGRATION_CATALOG.map(e => e.category))];
