import type { SkillDefinition, ToolDefinition } from '../skills.js';

export const SKILL_DEF: Omit<SkillDefinition, 'tools'> = {
  id: 'enterprise-notifications',
  name: 'Multi-Channel Notifications',
  description: 'Send notifications via email, Slack, Microsoft Teams, SMS, push notifications, and webhooks. Supports templates, priority routing, do-not-disturb rules, and escalation chains.',
  category: 'communication',
  risk: 'medium',
  icon: '🔔',
  source: 'builtin',
  version: '1.0.0',
  author: 'AgenticMail',
};

export const TOOLS: ToolDefinition[] = [
  {
    id: 'ent_notify_send',
    name: 'Send Notification',
    description: 'Send a notification to one or more recipients via their preferred channel. Automatically routes based on recipient preferences and urgency.',
    category: 'communicate',
    risk: 'medium',
    skillId: 'enterprise-notifications',
    sideEffects: ['sends-email', 'sends-message'],
    parameters: {
      type: 'object',
      properties: {
        recipients: { type: 'array', items: { type: 'string' }, description: 'Email addresses or user IDs' },
        title: { type: 'string', description: 'Notification title/subject' },
        message: { type: 'string', description: 'Notification body (supports Markdown)' },
        channel: { type: 'string', enum: ['auto', 'email', 'slack', 'teams', 'sms', 'push', 'webhook'], description: 'Delivery channel (auto=use recipient preferences)', default: 'auto' },
        priority: { type: 'string', enum: ['low', 'normal', 'high', 'critical'], default: 'normal' },
        actionUrl: { type: 'string', description: 'URL for the notification action button' },
        actionLabel: { type: 'string', description: 'Label for the action button' },
      },
      required: ['recipients', 'title', 'message'],
    },
  },
  {
    id: 'ent_notify_broadcast',
    name: 'Broadcast Announcement',
    description: 'Send a message to all members of a team, channel, or the entire organization. Supports scheduling for future delivery.',
    category: 'communicate',
    risk: 'high',
    skillId: 'enterprise-notifications',
    sideEffects: ['sends-email', 'sends-message'],
    parameters: {
      type: 'object',
      properties: {
        audience: { type: 'string', description: 'Team name, channel, "all-staff", or distribution list' },
        title: { type: 'string' },
        message: { type: 'string' },
        channels: { type: 'array', items: { type: 'string', enum: ['email', 'slack', 'teams'] }, description: 'Channels to broadcast on' },
        scheduledFor: { type: 'string', description: 'ISO 8601 datetime for scheduled delivery' },
      },
      required: ['audience', 'title', 'message'],
    },
  },
  {
    id: 'ent_notify_webhook',
    name: 'Send Webhook',
    description: 'Send a JSON payload to a webhook URL. Useful for triggering external automations, CI/CD pipelines, or custom integrations.',
    category: 'communicate',
    risk: 'medium',
    skillId: 'enterprise-notifications',
    sideEffects: ['network-request'],
    parameters: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'Webhook URL' },
        payload: { type: 'object', description: 'JSON payload to send' },
        method: { type: 'string', enum: ['POST', 'PUT'], default: 'POST' },
        headers: { type: 'object', description: 'Additional HTTP headers' },
        secret: { type: 'string', description: 'Webhook signing secret (from vault)' },
      },
      required: ['url', 'payload'],
    },
  },
  {
    id: 'ent_notify_escalate',
    name: 'Escalate Alert',
    description: 'Escalate an unacknowledged alert through the on-call chain. Follows the escalation policy with increasing urgency.',
    category: 'communicate',
    risk: 'high',
    skillId: 'enterprise-notifications',
    sideEffects: ['sends-email', 'sends-message', 'sends-sms'],
    parameters: {
      type: 'object',
      properties: {
        alertTitle: { type: 'string' },
        alertDescription: { type: 'string' },
        severity: { type: 'string', enum: ['info', 'warning', 'error', 'critical'] },
        escalationPolicy: { type: 'string', description: 'Named escalation policy to follow' },
        acknowledgeUrl: { type: 'string', description: 'URL to acknowledge the alert' },
      },
      required: ['alertTitle', 'alertDescription', 'severity'],
    },
  },
  {
    id: 'ent_notify_schedule',
    name: 'Schedule Recurring Notification',
    description: 'Set up a recurring notification on a schedule (daily digest, weekly report reminder, etc.).',
    category: 'write',
    risk: 'medium',
    skillId: 'enterprise-notifications',
    sideEffects: ['sends-email', 'sends-message'],
    parameters: {
      type: 'object',
      properties: {
        recipients: { type: 'array', items: { type: 'string' } },
        title: { type: 'string' },
        message: { type: 'string' },
        schedule: { type: 'string', description: 'Cron expression (e.g., "0 9 * * MON" for every Monday at 9am)' },
        channel: { type: 'string', enum: ['auto', 'email', 'slack', 'teams'], default: 'auto' },
        timezone: { type: 'string', default: 'UTC' },
      },
      required: ['recipients', 'title', 'message', 'schedule'],
    },
  },
];
