import type { SkillDefinition, ToolDefinition } from '../skills.js';

export const SKILL_DEF: Omit<SkillDefinition, 'tools'> = {
  id: 'enterprise-spreadsheet',
  name: 'Spreadsheet Processor',
  description: 'Read, write, transform, and analyze Excel and CSV files. Supports filtering, sorting, aggregations, pivot operations, formula computation, merging datasets, and format conversion. Handles large files with streaming.',
  category: 'data',
  risk: 'medium',
  icon: '📊',
  source: 'builtin',
  version: '1.0.0',
  author: 'AgenticMail',
};

export const TOOLS: ToolDefinition[] = [
  {
    id: 'ent_sheet_read',
    name: 'Read Spreadsheet',
    description: 'Read an Excel (.xlsx, .xls) or CSV file and return contents as structured data. Supports sheet selection, header row detection, and data type inference.',
    category: 'read',
    risk: 'low',
    skillId: 'enterprise-spreadsheet',
    sideEffects: [],
    parameters: {
      type: 'object',
      properties: {
        filePath: { type: 'string', description: 'Path to the spreadsheet file or URL' },
        sheet: { type: 'string', description: 'Sheet name (Excel only, default: first sheet)' },
        headerRow: { type: 'number', description: 'Row number containing headers (1-based, default: 1)', default: 1 },
        range: { type: 'string', description: 'Cell range to read (e.g., "A1:D100"). Omit for entire sheet.' },
        limit: { type: 'number', description: 'Maximum rows to return', default: 5000 },
        format: { type: 'string', enum: ['json', 'csv', 'markdown'], default: 'json' },
      },
      required: ['filePath'],
    },
  },
  {
    id: 'ent_sheet_write',
    name: 'Write Spreadsheet',
    description: 'Create or overwrite a spreadsheet file from structured data. Supports Excel and CSV output with formatting options.',
    category: 'write',
    risk: 'medium',
    skillId: 'enterprise-spreadsheet',
    sideEffects: ['modifies-files'],
    parameters: {
      type: 'object',
      properties: {
        outputPath: { type: 'string', description: 'Output file path (.xlsx or .csv)' },
        data: { type: 'array', items: { type: 'object' }, description: 'Array of row objects' },
        headers: { type: 'array', items: { type: 'string' }, description: 'Column headers (auto-detected from data if omitted)' },
        sheetName: { type: 'string', description: 'Sheet name (Excel only)', default: 'Sheet1' },
      },
      required: ['outputPath', 'data'],
    },
  },
  {
    id: 'ent_sheet_filter',
    name: 'Filter Rows',
    description: 'Filter spreadsheet rows by column conditions. Supports equals, contains, greater/less than, regex, and is-empty checks.',
    category: 'read',
    risk: 'low',
    skillId: 'enterprise-spreadsheet',
    sideEffects: [],
    parameters: {
      type: 'object',
      properties: {
        filePath: { type: 'string', description: 'Path to spreadsheet' },
        filters: { type: 'array', items: { type: 'object', properties: { column: { type: 'string' }, operator: { type: 'string', enum: ['eq', 'neq', 'gt', 'lt', 'gte', 'lte', 'contains', 'not_contains', 'starts_with', 'ends_with', 'regex', 'is_empty', 'not_empty'] }, value: { type: 'string' } } }, description: 'Filter conditions' },
        sheet: { type: 'string', description: 'Sheet name (Excel only)' },
      },
      required: ['filePath', 'filters'],
    },
  },
  {
    id: 'ent_sheet_aggregate',
    name: 'Aggregate Data',
    description: 'Compute aggregations over spreadsheet data: sum, average, count, min, max, median, std deviation. Supports grouping by columns (like SQL GROUP BY).',
    category: 'read',
    risk: 'low',
    skillId: 'enterprise-spreadsheet',
    sideEffects: [],
    parameters: {
      type: 'object',
      properties: {
        filePath: { type: 'string', description: 'Path to spreadsheet' },
        groupBy: { type: 'array', items: { type: 'string' }, description: 'Columns to group by' },
        aggregations: { type: 'array', items: { type: 'object', properties: { column: { type: 'string' }, function: { type: 'string', enum: ['sum', 'avg', 'count', 'min', 'max', 'median', 'stddev'] } } }, description: 'Aggregation operations' },
        sheet: { type: 'string' },
      },
      required: ['filePath', 'aggregations'],
    },
  },
  {
    id: 'ent_sheet_transform',
    name: 'Transform Columns',
    description: 'Add, rename, reorder, or compute new columns. Supports formulas, string operations, date parsing, and type casting.',
    category: 'write',
    risk: 'low',
    skillId: 'enterprise-spreadsheet',
    sideEffects: [],
    parameters: {
      type: 'object',
      properties: {
        filePath: { type: 'string', description: 'Path to spreadsheet' },
        transforms: { type: 'array', items: { type: 'object', properties: { action: { type: 'string', enum: ['add', 'rename', 'drop', 'reorder', 'cast'] }, column: { type: 'string' }, newName: { type: 'string' }, formula: { type: 'string' }, dataType: { type: 'string', enum: ['string', 'number', 'date', 'boolean'] } } } },
        outputPath: { type: 'string', description: 'Output file (or overwrite source if omitted)' },
      },
      required: ['filePath', 'transforms'],
    },
  },
  {
    id: 'ent_sheet_merge',
    name: 'Merge Datasets',
    description: 'Join two spreadsheets by matching columns (like SQL JOIN). Supports inner, left, right, and full outer joins.',
    category: 'read',
    risk: 'low',
    skillId: 'enterprise-spreadsheet',
    sideEffects: [],
    parameters: {
      type: 'object',
      properties: {
        leftFile: { type: 'string', description: 'Path to left spreadsheet' },
        rightFile: { type: 'string', description: 'Path to right spreadsheet' },
        joinType: { type: 'string', enum: ['inner', 'left', 'right', 'full'], default: 'inner' },
        leftKey: { type: 'string', description: 'Column name in left file to join on' },
        rightKey: { type: 'string', description: 'Column name in right file to join on' },
        outputPath: { type: 'string', description: 'Output file path' },
      },
      required: ['leftFile', 'rightFile', 'leftKey', 'rightKey'],
    },
  },
  {
    id: 'ent_sheet_pivot',
    name: 'Pivot Table',
    description: 'Create a pivot table from spreadsheet data. Group by row and column dimensions, aggregate with sum/avg/count.',
    category: 'read',
    risk: 'low',
    skillId: 'enterprise-spreadsheet',
    sideEffects: [],
    parameters: {
      type: 'object',
      properties: {
        filePath: { type: 'string', description: 'Path to spreadsheet' },
        rows: { type: 'array', items: { type: 'string' }, description: 'Row grouping columns' },
        columns: { type: 'array', items: { type: 'string' }, description: 'Column grouping columns' },
        values: { type: 'string', description: 'Value column to aggregate' },
        aggregation: { type: 'string', enum: ['sum', 'avg', 'count', 'min', 'max'], default: 'sum' },
      },
      required: ['filePath', 'rows', 'values'],
    },
  },
  {
    id: 'ent_sheet_convert',
    name: 'Convert Format',
    description: 'Convert between spreadsheet formats: Excel to CSV, CSV to Excel, CSV to JSON, JSON to CSV, Excel to JSON.',
    category: 'write',
    risk: 'low',
    skillId: 'enterprise-spreadsheet',
    sideEffects: ['modifies-files'],
    parameters: {
      type: 'object',
      properties: {
        inputPath: { type: 'string', description: 'Input file path' },
        outputPath: { type: 'string', description: 'Output file path (format inferred from extension)' },
        sheet: { type: 'string', description: 'Sheet to convert (Excel only)' },
      },
      required: ['inputPath', 'outputPath'],
    },
  },
];
