import type { SkillDefinition, ToolDefinition } from '../skills.js';

export const SKILL_DEF: Omit<SkillDefinition, 'tools'> = {
  id: 'enterprise-calendar',
  name: 'Calendar & Scheduling',
  description: 'Manage calendar events, check availability, schedule meetings, and handle timezone conversions. Works with connected calendar providers (Google Calendar, Outlook, CalDAV) or a built-in scheduling engine.',
  category: 'productivity',
  risk: 'medium',
  icon: '📅',
  source: 'builtin',
  version: '1.0.0',
  author: 'AgenticMail',
};

export const TOOLS: ToolDefinition[] = [
  {
    id: 'ent_cal_list_events',
    name: 'List Events',
    description: 'List calendar events within a date range. Returns event title, time, duration, attendees, location, and description.',
    category: 'read',
    risk: 'low',
    skillId: 'enterprise-calendar',
    sideEffects: ['network-request'],
    parameters: {
      type: 'object',
      properties: {
        calendarId: { type: 'string', description: 'Calendar ID or "primary"', default: 'primary' },
        startDate: { type: 'string', description: 'Start date (ISO 8601, e.g., "2024-01-15")' },
        endDate: { type: 'string', description: 'End date (ISO 8601)' },
        timezone: { type: 'string', description: 'Timezone (e.g., "America/New_York")', default: 'UTC' },
      },
      required: ['startDate', 'endDate'],
    },
  },
  {
    id: 'ent_cal_create_event',
    name: 'Create Event',
    description: 'Create a new calendar event with attendees, location, description, and reminders. Sends invitations to attendees.',
    category: 'write',
    risk: 'medium',
    skillId: 'enterprise-calendar',
    sideEffects: ['sends-email', 'network-request'],
    parameters: {
      type: 'object',
      properties: {
        title: { type: 'string', description: 'Event title' },
        startTime: { type: 'string', description: 'Start time (ISO 8601 with timezone)' },
        endTime: { type: 'string', description: 'End time (ISO 8601)' },
        attendees: { type: 'array', items: { type: 'string' }, description: 'Email addresses of attendees' },
        location: { type: 'string', description: 'Event location or video call link' },
        description: { type: 'string', description: 'Event description/agenda' },
        calendarId: { type: 'string', default: 'primary' },
        reminders: { type: 'array', items: { type: 'object', properties: { method: { type: 'string', enum: ['email', 'popup'] }, minutes: { type: 'number' } } } },
        recurrence: { type: 'string', description: 'RRULE string (e.g., "FREQ=WEEKLY;COUNT=10")' },
        videoConference: { type: 'boolean', description: 'Auto-create video meeting link', default: false },
      },
      required: ['title', 'startTime', 'endTime'],
    },
  },
  {
    id: 'ent_cal_find_availability',
    name: 'Find Available Slots',
    description: 'Find mutually available time slots across multiple attendees. Returns open windows matching duration and business hours constraints.',
    category: 'read',
    risk: 'low',
    skillId: 'enterprise-calendar',
    sideEffects: ['network-request'],
    parameters: {
      type: 'object',
      properties: {
        attendees: { type: 'array', items: { type: 'string' }, description: 'Email addresses to check availability for' },
        dateRange: { type: 'object', properties: { start: { type: 'string' }, end: { type: 'string' } }, description: 'Date range to search' },
        duration: { type: 'number', description: 'Meeting duration in minutes' },
        timezone: { type: 'string', default: 'UTC' },
        businessHours: { type: 'object', properties: { start: { type: 'string', description: 'e.g., "09:00"' }, end: { type: 'string', description: 'e.g., "17:00"' } } },
        maxResults: { type: 'number', description: 'Maximum slots to return', default: 5 },
      },
      required: ['attendees', 'dateRange', 'duration'],
    },
  },
  {
    id: 'ent_cal_update_event',
    name: 'Update Event',
    description: 'Update an existing calendar event. Can modify title, time, attendees, description, or location.',
    category: 'write',
    risk: 'medium',
    skillId: 'enterprise-calendar',
    sideEffects: ['sends-email', 'network-request'],
    parameters: {
      type: 'object',
      properties: {
        eventId: { type: 'string', description: 'Event ID to update' },
        calendarId: { type: 'string', default: 'primary' },
        title: { type: 'string' },
        startTime: { type: 'string' },
        endTime: { type: 'string' },
        attendees: { type: 'array', items: { type: 'string' } },
        location: { type: 'string' },
        description: { type: 'string' },
        sendUpdates: { type: 'boolean', description: 'Notify attendees of changes', default: true },
      },
      required: ['eventId'],
    },
  },
  {
    id: 'ent_cal_cancel_event',
    name: 'Cancel Event',
    description: 'Cancel a calendar event and optionally notify attendees.',
    category: 'destroy',
    risk: 'medium',
    skillId: 'enterprise-calendar',
    sideEffects: ['sends-email', 'network-request', 'deletes-data'],
    parameters: {
      type: 'object',
      properties: {
        eventId: { type: 'string', description: 'Event ID to cancel' },
        calendarId: { type: 'string', default: 'primary' },
        notifyAttendees: { type: 'boolean', default: true },
        cancellationMessage: { type: 'string', description: 'Message to include in cancellation notification' },
      },
      required: ['eventId'],
    },
  },
  {
    id: 'ent_cal_timezone_convert',
    name: 'Convert Timezone',
    description: 'Convert a date/time between timezones. Useful for scheduling across global teams.',
    category: 'read',
    risk: 'low',
    skillId: 'enterprise-calendar',
    sideEffects: [],
    parameters: {
      type: 'object',
      properties: {
        dateTime: { type: 'string', description: 'Date/time to convert (ISO 8601)' },
        fromTimezone: { type: 'string', description: 'Source timezone' },
        toTimezones: { type: 'array', items: { type: 'string' }, description: 'Target timezones to convert to' },
      },
      required: ['dateTime', 'fromTimezone', 'toTimezones'],
    },
  },
];
