import { Emoji } from '../emoji.js';
import type { SkillDefinition, ToolDefinition } from '../skills.js';

export const SKILL_DEF: Omit<SkillDefinition, 'tools'> = {
  id: 'remotion-video',
  name: 'Video Creation (Remotion)',
  description: 'Create professional marketing videos, social media reels, animations, and motion graphics programmatically using Remotion. Build React-based video compositions, render to MP4/WebM/GIF, and manage video projects. Supports text animations, image slideshows, data visualizations, branded intros/outros, and more.',
  category: 'media',
  risk: 'medium',
  icon: Emoji.movie,
  source: 'builtin',
  version: '1.0.0',
  author: 'AgenticMail',
};

export const TOOLS: ToolDefinition[] = [
  {
    id: 'remotion_create_project',
    name: 'Create Video Project',
    description: 'Initialize a new Remotion video project in a workspace directory. Sets up the project structure with package.json, tsconfig, and a starter composition. Use this before creating compositions.',
    category: 'write',
    risk: 'medium',
    skillId: 'remotion-video',
    sideEffects: ['modifies-files', 'installs-packages'],
    parameters: {
      type: 'object',
      properties: {
        projectDir: { type: 'string', description: 'Directory path for the video project (e.g., "/workspace/videos/my-project")' },
        name: { type: 'string', description: 'Project name (used in package.json)' },
        template: { type: 'string', enum: ['blank', 'hello-world', 'text-animation', 'slideshow', 'social-reel'], default: 'blank', description: 'Starter template to use' },
      },
      required: ['projectDir'],
    },
  },
  {
    id: 'remotion_create_composition',
    name: 'Create Video Composition',
    description: 'Create or update a Remotion composition (React component) that defines a video. Write the JSX/TSX component code that will be rendered as a video. The composition defines what appears in each frame — text, images, animations, transitions, etc. Use React patterns: useCurrentFrame(), interpolate(), spring(), Sequence, AbsoluteFill.',
    category: 'write',
    risk: 'low',
    skillId: 'remotion-video',
    sideEffects: ['modifies-files'],
    parameters: {
      type: 'object',
      properties: {
        projectDir: { type: 'string', description: 'Path to the Remotion project directory' },
        compositionId: { type: 'string', description: 'Unique ID for this composition (e.g., "marketing-reel", "product-demo")' },
        code: { type: 'string', description: 'Full React component code (TSX) for the composition. Use Remotion APIs: useCurrentFrame(), interpolate(), spring(), Sequence, AbsoluteFill, Img, Audio, Video, etc.' },
        width: { type: 'number', default: 1080, description: 'Video width in pixels' },
        height: { type: 'number', default: 1920, description: 'Video height in pixels (1920 for 9:16 vertical reels, 1080 for 16:9 landscape)' },
        fps: { type: 'number', default: 30, description: 'Frames per second' },
        durationInSeconds: { type: 'number', default: 15, description: 'Video duration in seconds' },
      },
      required: ['projectDir', 'compositionId', 'code'],
    },
  },
  {
    id: 'remotion_render',
    name: 'Render Video',
    description: 'Render a Remotion composition to a video file (MP4, WebM, or GIF). This bundles the React project and renders each frame using a headless browser, then encodes the final video. Requires ffmpeg to be installed.',
    category: 'write',
    risk: 'medium',
    skillId: 'remotion-video',
    sideEffects: ['modifies-files', 'cpu-intensive'],
    parameters: {
      type: 'object',
      properties: {
        projectDir: { type: 'string', description: 'Path to the Remotion project directory' },
        compositionId: { type: 'string', description: 'ID of the composition to render' },
        outputPath: { type: 'string', description: 'Output file path (e.g., "/workspace/videos/output.mp4")' },
        codec: { type: 'string', enum: ['h264', 'h265', 'vp8', 'vp9', 'gif', 'prores'], default: 'h264', description: 'Video codec' },
        quality: { type: 'number', description: 'Quality (0-100, default varies by codec). For h264: crf value (lower = better, 18 is visually lossless)' },
        inputProps: { type: 'object', description: 'Props to pass to the composition (e.g., text content, image URLs, colors)' },
        concurrency: { type: 'number', description: 'Number of frames to render in parallel (default: half of CPU cores)' },
        scale: { type: 'number', default: 1, description: 'Scale factor for rendering (2 = 2x resolution)' },
      },
      required: ['projectDir', 'compositionId', 'outputPath'],
    },
  },
  {
    id: 'remotion_render_still',
    name: 'Render Still Image',
    description: 'Render a single frame from a Remotion composition as a PNG or JPEG image. Useful for thumbnails, social media images, or previewing a specific frame of a video.',
    category: 'write',
    risk: 'low',
    skillId: 'remotion-video',
    sideEffects: ['modifies-files'],
    parameters: {
      type: 'object',
      properties: {
        projectDir: { type: 'string', description: 'Path to the Remotion project directory' },
        compositionId: { type: 'string', description: 'ID of the composition' },
        outputPath: { type: 'string', description: 'Output image path (.png or .jpg)' },
        frame: { type: 'number', default: 0, description: 'Frame number to render' },
        inputProps: { type: 'object', description: 'Props to pass to the composition' },
        format: { type: 'string', enum: ['png', 'jpeg', 'webp'], default: 'png' },
        scale: { type: 'number', default: 1 },
      },
      required: ['projectDir', 'compositionId', 'outputPath'],
    },
  },
  {
    id: 'remotion_list_compositions',
    name: 'List Compositions',
    description: 'List all available compositions in a Remotion project with their IDs, dimensions, duration, and FPS.',
    category: 'read',
    risk: 'low',
    skillId: 'remotion-video',
    sideEffects: [],
    parameters: {
      type: 'object',
      properties: {
        projectDir: { type: 'string', description: 'Path to the Remotion project directory' },
      },
      required: ['projectDir'],
    },
  },
  {
    id: 'remotion_preview_url',
    name: 'Start Preview Server',
    description: 'Start the Remotion Studio preview server so you can preview compositions in the browser. Returns the URL to access the studio.',
    category: 'read',
    risk: 'low',
    skillId: 'remotion-video',
    sideEffects: ['starts-process'],
    parameters: {
      type: 'object',
      properties: {
        projectDir: { type: 'string', description: 'Path to the Remotion project directory' },
        port: { type: 'number', default: 3333, description: 'Port for the preview server' },
      },
      required: ['projectDir'],
    },
  },
  {
    id: 'remotion_add_asset',
    name: 'Add Asset to Project',
    description: 'Add an image, audio, font, or video asset to a Remotion project. Downloads from URL or copies from local path into the project\'s public/ directory so it can be referenced in compositions via staticFile().',
    category: 'write',
    risk: 'low',
    skillId: 'remotion-video',
    sideEffects: ['modifies-files'],
    parameters: {
      type: 'object',
      properties: {
        projectDir: { type: 'string', description: 'Path to the Remotion project directory' },
        source: { type: 'string', description: 'URL or local file path of the asset to add' },
        filename: { type: 'string', description: 'Filename to save as in public/ directory (e.g., "background.mp3", "logo.png")' },
      },
      required: ['projectDir', 'source', 'filename'],
    },
  },
  {
    id: 'remotion_install_package',
    name: 'Install Remotion Package',
    description: 'Install additional Remotion packages or dependencies into a project. Common packages: @remotion/transitions (scene transitions), @remotion/motion-blur, @remotion/noise, @remotion/paths, @remotion/shapes, @remotion/lottie (After Effects animations), @remotion/three (3D graphics).',
    category: 'write',
    risk: 'medium',
    skillId: 'remotion-video',
    sideEffects: ['installs-packages'],
    parameters: {
      type: 'object',
      properties: {
        projectDir: { type: 'string', description: 'Path to the Remotion project directory' },
        packages: { type: 'array', items: { type: 'string' }, description: 'Package names to install (e.g., ["@remotion/transitions", "@remotion/shapes"])' },
      },
      required: ['projectDir', 'packages'],
    },
  },
];
