/**
 * Integration Tools — All 3rd-party service integrations
 *
 * 144 integrations with 650+ tools.
 * Each file wraps an MCP adapter into native agent tools.
 * Tools are only created when vault credentials exist.
 *
 * Auto-generated by scripts/generate-integration-tools.js
 * Do not edit manually.
 */

import type { AnyAgentTool } from '../../types.js';
import type { IntegrationConfig } from './_factory.js';
export type { IntegrationConfig } from './_factory.js';

// ─── Individual exports ─────────────────────────────────

export { createActivecampaignTools } from './activecampaign.js';
export { createAdobeSignTools } from './adobe-sign.js';
export { createAdpTools } from './adp.js';
export { createAirtableBasesTools } from './airtable.js';
export { createApolloIoTools } from './apollo.js';
export { createAsanaTasksTools } from './asana.js';
export { createAuth0Tools } from './auth0.js';
export { createAwsServicesTools } from './aws.js';
export { createAzureDevopsTools } from './azure-devops.js';
export { createBamboohrTools } from './bamboohr.js';
export { createBasecampTools } from './basecamp.js';
export { createBigcommerceTools } from './bigcommerce.js';
export { createBitbucketReposTools } from './bitbucket.js';
export { createBoxTools } from './box.js';
export { createBrexTools } from './brex.js';
export { createBufferTools } from './buffer.js';
export { createCalendlyTools } from './calendly.js';
export { createCanvaDesignTools } from './canva.js';
export { createChargebeeTools } from './chargebee.js';
export { createCircleciPipelinesTools } from './circleci.js';
export { createClickupTools } from './clickup.js';
export { createCloseCrmTools } from './close.js';
export { createCloudflareCdnTools } from './cloudflare.js';
export { createConfluenceWikiTools } from './confluence.js';
export { createContentfulTools } from './contentful.js';
export { createCopperCrmTools } from './copper.js';
export { createCrispTools } from './crisp.js';
export { createCrowdstrikeTools } from './crowdstrike.js';
export { createDatadogMonitoringTools } from './datadog.js';
export { createDigitaloceanTools } from './digitalocean.js';
export { createDiscordTools } from './discord.js';
export { createDockerContainersTools } from './docker.js';
export { createDocusignEsignTools } from './docusign.js';
export { createDriftTools } from './drift.js';
export { createDropboxStorageTools } from './dropbox.js';
export { createFigmaDesignTools } from './figma.js';
export { createFirebaseTools } from './firebase.js';
export { createFlyioTools } from './flyio.js';
export { createFreshbooksTools } from './freshbooks.js';
export { createFreshdeskTools } from './freshdesk.js';
export { createFreshsalesTools } from './freshsales.js';
export { createFreshserviceTools } from './freshservice.js';
export { createFrontTools } from './front.js';
export { createGithubActionsTools } from './github-actions.js';
export { createGithubTools } from './github.js';
export { createGitlabCiTools } from './gitlab.js';
export { createGongTools } from './gong.js';
export { createGoogleAdsTools } from './google-ads.js';
export { createGoogleAnalyticsTools } from './google-analytics.js';
export { createGoogleCloudTools } from './google-cloud.js';
export { createGotomeetingTools } from './gotomeeting.js';
export { createGrafanaTools } from './grafana.js';
export { createGreenhouseTools } from './greenhouse.js';
export { createGustoTools } from './gusto.js';
export { createHashicorpVaultTools } from './hashicorp-vault.js';
export { createHerokuTools } from './heroku.js';
export { createHibobTools } from './hibob.js';
export { createHootsuiteTools } from './hootsuite.js';
export { createHubspotCrmTools } from './hubspot.js';
export { createHuggingfaceTools } from './huggingface.js';
export { createIntercomSupportTools } from './intercom.js';
export { createJiraTools } from './jira.js';
export { createKlaviyoTools } from './klaviyo.js';
export { createKubernetesClusterTools } from './kubernetes.js';
export { createLatticeTools } from './lattice.js';
export { createLaunchdarklyTools } from './launchdarkly.js';
export { createLeverTools } from './lever.js';
export { createLinearTools } from './linear.js';
export { createLinkedinTools } from './linkedin.js';
export { createLivechatTools } from './livechat.js';
export { createLoomVideoTools } from './loom.js';
export { createMailchimpCampaignsTools } from './mailchimp.js';
export { createMailgunTools } from './mailgun.js';
export { createMiroBoardsTools } from './miro.js';
export { createMixpanelAnalyticsTools } from './mixpanel.js';
export { createMondayBoardsTools } from './monday.js';
export { createMongodbAtlasTools } from './mongodb-atlas.js';
export { createNeonTools } from './neon.js';
export { createNetlifyTools } from './netlify.js';
export { createNetsuiteTools } from './netsuite.js';
export { createNewrelicTools } from './newrelic.js';
export { createNotionTools } from './notion.js';
export { createOktaTools } from './okta.js';
export { createOpenaiTools } from './openai.js';
export { createOpsgenieTools } from './opsgenie.js';
export { createOutreachTools } from './outreach.js';
export { createPaddleTools } from './paddle.js';
export { createPagerdutyTools } from './pagerduty.js';
export { createPandadocTools } from './pandadoc.js';
export { createPaypalTools } from './paypal.js';
export { createPersonioTools } from './personio.js';
export { createPineconeTools } from './pinecone.js';
export { createPipedriveDealsTools } from './pipedrive.js';
export { createPlaidTools } from './plaid.js';
export { createPostmarkTools } from './postmark.js';
export { createPowerAutomateTools } from './power-automate.js';
export { createQuickbooksAccountingTools } from './quickbooks.js';
export { createRecurlyTools } from './recurly.js';
export { createRedditTools } from './reddit.js';
export { createRenderTools } from './render.js';
export { createRingcentralTools } from './ringcentral.js';
export { createRipplingTools } from './rippling.js';
export { createSalesforceTools } from './salesforce.js';
export { createSalesloftTools } from './salesloft.js';
export { createSanityTools } from './sanity.js';
export { createSapTools } from './sap.js';
export { createSegmentCdpTools } from './segment.js';
export { createSendgridEmailTools } from './sendgrid.js';
export { createSentryTools } from './sentry.js';
export { createServicenowTools } from './servicenow.js';
export { createShopifyTools } from './shopify.js';
export { createShortcutTools } from './shortcut.js';
export { createSlackTools } from './slack.js';
export { createSmartsheetTools } from './smartsheet.js';
export { createSnowflakeWarehouseTools } from './snowflake.js';
export { createSnykTools } from './snyk.js';
export { createSplunkTools } from './splunk.js';
export { createSquareTools } from './square.js';
export { createStatuspageTools } from './statuspage.js';
export { createStripeTools } from './stripe.js';
export { createSupabaseTools } from './supabase.js';
export { createTeamworkTools } from './teamwork.js';
export { createTelegramBotTools } from './telegram.js';
export { createTerraformIacTools } from './terraform.js';
export { createTodoistTasksTools } from './todoist.js';
export { createTrelloCardsTools } from './trello.js';
export { createTwilioSmsTools } from './twilio.js';
export { createTwitterTools } from './twitter.js';
export { createVercelDeploymentsTools } from './vercel.js';
export { createWeaviateTools } from './weaviate.js';
export { createWebexTools } from './webex.js';
export { createWebflowTools } from './webflow.js';
export { createWhatsappBusinessTools } from './whatsapp.js';
export { createWherebyTools } from './whereby.js';
export { createWoocommerceTools } from './woocommerce.js';
export { createWordpressTools } from './wordpress.js';
export { createWorkdayTools } from './workday.js';
export { createWrikeTools } from './wrike.js';
export { createXeroTools } from './xero.js';
export { createYoutubeTools } from './youtube.js';
export { createZendeskTicketsTools } from './zendesk.js';
export { createZohoCrmTools } from './zoho-crm.js';
export { createZoomMeetingsTools } from './zoom.js';
export { createZuoraTools } from './zuora.js';

// ─── Imports for createAllIntegrationTools ───────────

import { createActivecampaignTools } from './activecampaign.js';
import { createAdobeSignTools } from './adobe-sign.js';
import { createAdpTools } from './adp.js';
import { createAirtableBasesTools } from './airtable.js';
import { createApolloIoTools } from './apollo.js';
import { createAsanaTasksTools } from './asana.js';
import { createAuth0Tools } from './auth0.js';
import { createAwsServicesTools } from './aws.js';
import { createAzureDevopsTools } from './azure-devops.js';
import { createBamboohrTools } from './bamboohr.js';
import { createBasecampTools } from './basecamp.js';
import { createBigcommerceTools } from './bigcommerce.js';
import { createBitbucketReposTools } from './bitbucket.js';
import { createBoxTools } from './box.js';
import { createBrexTools } from './brex.js';
import { createBufferTools } from './buffer.js';
import { createCalendlyTools } from './calendly.js';
import { createCanvaDesignTools } from './canva.js';
import { createChargebeeTools } from './chargebee.js';
import { createCircleciPipelinesTools } from './circleci.js';
import { createClickupTools } from './clickup.js';
import { createCloseCrmTools } from './close.js';
import { createCloudflareCdnTools } from './cloudflare.js';
import { createConfluenceWikiTools } from './confluence.js';
import { createContentfulTools } from './contentful.js';
import { createCopperCrmTools } from './copper.js';
import { createCrispTools } from './crisp.js';
import { createCrowdstrikeTools } from './crowdstrike.js';
import { createDatadogMonitoringTools } from './datadog.js';
import { createDigitaloceanTools } from './digitalocean.js';
import { createDiscordTools } from './discord.js';
import { createDockerContainersTools } from './docker.js';
import { createDocusignEsignTools } from './docusign.js';
import { createDriftTools } from './drift.js';
import { createDropboxStorageTools } from './dropbox.js';
import { createFigmaDesignTools } from './figma.js';
import { createFirebaseTools } from './firebase.js';
import { createFlyioTools } from './flyio.js';
import { createFreshbooksTools } from './freshbooks.js';
import { createFreshdeskTools } from './freshdesk.js';
import { createFreshsalesTools } from './freshsales.js';
import { createFreshserviceTools } from './freshservice.js';
import { createFrontTools } from './front.js';
import { createGithubActionsTools } from './github-actions.js';
import { createGithubTools } from './github.js';
import { createGitlabCiTools } from './gitlab.js';
import { createGongTools } from './gong.js';
import { createGoogleAdsTools } from './google-ads.js';
import { createGoogleAnalyticsTools } from './google-analytics.js';
import { createGoogleCloudTools } from './google-cloud.js';
import { createGotomeetingTools } from './gotomeeting.js';
import { createGrafanaTools } from './grafana.js';
import { createGreenhouseTools } from './greenhouse.js';
import { createGustoTools } from './gusto.js';
import { createHashicorpVaultTools } from './hashicorp-vault.js';
import { createHerokuTools } from './heroku.js';
import { createHibobTools } from './hibob.js';
import { createHootsuiteTools } from './hootsuite.js';
import { createHubspotCrmTools } from './hubspot.js';
import { createHuggingfaceTools } from './huggingface.js';
import { createIntercomSupportTools } from './intercom.js';
import { createJiraTools } from './jira.js';
import { createKlaviyoTools } from './klaviyo.js';
import { createKubernetesClusterTools } from './kubernetes.js';
import { createLatticeTools } from './lattice.js';
import { createLaunchdarklyTools } from './launchdarkly.js';
import { createLeverTools } from './lever.js';
import { createLinearTools } from './linear.js';
import { createLinkedinTools } from './linkedin.js';
import { createLivechatTools } from './livechat.js';
import { createLoomVideoTools } from './loom.js';
import { createMailchimpCampaignsTools } from './mailchimp.js';
import { createMailgunTools } from './mailgun.js';
import { createMiroBoardsTools } from './miro.js';
import { createMixpanelAnalyticsTools } from './mixpanel.js';
import { createMondayBoardsTools } from './monday.js';
import { createMongodbAtlasTools } from './mongodb-atlas.js';
import { createNeonTools } from './neon.js';
import { createNetlifyTools } from './netlify.js';
import { createNetsuiteTools } from './netsuite.js';
import { createNewrelicTools } from './newrelic.js';
import { createNotionTools } from './notion.js';
import { createOktaTools } from './okta.js';
import { createOpenaiTools } from './openai.js';
import { createOpsgenieTools } from './opsgenie.js';
import { createOutreachTools } from './outreach.js';
import { createPaddleTools } from './paddle.js';
import { createPagerdutyTools } from './pagerduty.js';
import { createPandadocTools } from './pandadoc.js';
import { createPaypalTools } from './paypal.js';
import { createPersonioTools } from './personio.js';
import { createPineconeTools } from './pinecone.js';
import { createPipedriveDealsTools } from './pipedrive.js';
import { createPlaidTools } from './plaid.js';
import { createPostmarkTools } from './postmark.js';
import { createPowerAutomateTools } from './power-automate.js';
import { createQuickbooksAccountingTools } from './quickbooks.js';
import { createRecurlyTools } from './recurly.js';
import { createRedditTools } from './reddit.js';
import { createRenderTools } from './render.js';
import { createRingcentralTools } from './ringcentral.js';
import { createRipplingTools } from './rippling.js';
import { createSalesforceTools } from './salesforce.js';
import { createSalesloftTools } from './salesloft.js';
import { createSanityTools } from './sanity.js';
import { createSapTools } from './sap.js';
import { createSegmentCdpTools } from './segment.js';
import { createSendgridEmailTools } from './sendgrid.js';
import { createSentryTools } from './sentry.js';
import { createServicenowTools } from './servicenow.js';
import { createShopifyTools } from './shopify.js';
import { createShortcutTools } from './shortcut.js';
import { createSlackTools } from './slack.js';
import { createSmartsheetTools } from './smartsheet.js';
import { createSnowflakeWarehouseTools } from './snowflake.js';
import { createSnykTools } from './snyk.js';
import { createSplunkTools } from './splunk.js';
import { createSquareTools } from './square.js';
import { createStatuspageTools } from './statuspage.js';
import { createStripeTools } from './stripe.js';
import { createSupabaseTools } from './supabase.js';
import { createTeamworkTools } from './teamwork.js';
import { createTelegramBotTools } from './telegram.js';
import { createTerraformIacTools } from './terraform.js';
import { createTodoistTasksTools } from './todoist.js';
import { createTrelloCardsTools } from './trello.js';
import { createTwilioSmsTools } from './twilio.js';
import { createTwitterTools } from './twitter.js';
import { createVercelDeploymentsTools } from './vercel.js';
import { createWeaviateTools } from './weaviate.js';
import { createWebexTools } from './webex.js';
import { createWebflowTools } from './webflow.js';
import { createWhatsappBusinessTools } from './whatsapp.js';
import { createWherebyTools } from './whereby.js';
import { createWoocommerceTools } from './woocommerce.js';
import { createWordpressTools } from './wordpress.js';
import { createWorkdayTools } from './workday.js';
import { createWrikeTools } from './wrike.js';
import { createXeroTools } from './xero.js';
import { createYoutubeTools } from './youtube.js';
import { createZendeskTicketsTools } from './zendesk.js';
import { createZohoCrmTools } from './zoho-crm.js';
import { createZoomMeetingsTools } from './zoom.js';
import { createZuoraTools } from './zuora.js';

/** All integration tool creators */
const ALL_CREATORS: Array<(config: IntegrationConfig) => Promise<AnyAgentTool[]>> = [
  createActivecampaignTools,
  createAdobeSignTools,
  createAdpTools,
  createAirtableBasesTools,
  createApolloIoTools,
  createAsanaTasksTools,
  createAuth0Tools,
  createAwsServicesTools,
  createAzureDevopsTools,
  createBamboohrTools,
  createBasecampTools,
  createBigcommerceTools,
  createBitbucketReposTools,
  createBoxTools,
  createBrexTools,
  createBufferTools,
  createCalendlyTools,
  createCanvaDesignTools,
  createChargebeeTools,
  createCircleciPipelinesTools,
  createClickupTools,
  createCloseCrmTools,
  createCloudflareCdnTools,
  createConfluenceWikiTools,
  createContentfulTools,
  createCopperCrmTools,
  createCrispTools,
  createCrowdstrikeTools,
  createDatadogMonitoringTools,
  createDigitaloceanTools,
  createDiscordTools,
  createDockerContainersTools,
  createDocusignEsignTools,
  createDriftTools,
  createDropboxStorageTools,
  createFigmaDesignTools,
  createFirebaseTools,
  createFlyioTools,
  createFreshbooksTools,
  createFreshdeskTools,
  createFreshsalesTools,
  createFreshserviceTools,
  createFrontTools,
  createGithubActionsTools,
  createGithubTools,
  createGitlabCiTools,
  createGongTools,
  createGoogleAdsTools,
  createGoogleAnalyticsTools,
  createGoogleCloudTools,
  createGotomeetingTools,
  createGrafanaTools,
  createGreenhouseTools,
  createGustoTools,
  createHashicorpVaultTools,
  createHerokuTools,
  createHibobTools,
  createHootsuiteTools,
  createHubspotCrmTools,
  createHuggingfaceTools,
  createIntercomSupportTools,
  createJiraTools,
  createKlaviyoTools,
  createKubernetesClusterTools,
  createLatticeTools,
  createLaunchdarklyTools,
  createLeverTools,
  createLinearTools,
  createLinkedinTools,
  createLivechatTools,
  createLoomVideoTools,
  createMailchimpCampaignsTools,
  createMailgunTools,
  createMiroBoardsTools,
  createMixpanelAnalyticsTools,
  createMondayBoardsTools,
  createMongodbAtlasTools,
  createNeonTools,
  createNetlifyTools,
  createNetsuiteTools,
  createNewrelicTools,
  createNotionTools,
  createOktaTools,
  createOpenaiTools,
  createOpsgenieTools,
  createOutreachTools,
  createPaddleTools,
  createPagerdutyTools,
  createPandadocTools,
  createPaypalTools,
  createPersonioTools,
  createPineconeTools,
  createPipedriveDealsTools,
  createPlaidTools,
  createPostmarkTools,
  createPowerAutomateTools,
  createQuickbooksAccountingTools,
  createRecurlyTools,
  createRedditTools,
  createRenderTools,
  createRingcentralTools,
  createRipplingTools,
  createSalesforceTools,
  createSalesloftTools,
  createSanityTools,
  createSapTools,
  createSegmentCdpTools,
  createSendgridEmailTools,
  createSentryTools,
  createServicenowTools,
  createShopifyTools,
  createShortcutTools,
  createSlackTools,
  createSmartsheetTools,
  createSnowflakeWarehouseTools,
  createSnykTools,
  createSplunkTools,
  createSquareTools,
  createStatuspageTools,
  createStripeTools,
  createSupabaseTools,
  createTeamworkTools,
  createTelegramBotTools,
  createTerraformIacTools,
  createTodoistTasksTools,
  createTrelloCardsTools,
  createTwilioSmsTools,
  createTwitterTools,
  createVercelDeploymentsTools,
  createWeaviateTools,
  createWebexTools,
  createWebflowTools,
  createWhatsappBusinessTools,
  createWherebyTools,
  createWoocommerceTools,
  createWordpressTools,
  createWorkdayTools,
  createWrikeTools,
  createXeroTools,
  createYoutubeTools,
  createZendeskTicketsTools,
  createZohoCrmTools,
  createZoomMeetingsTools,
  createZuoraTools,
];

/**
 * Create all integration tools that have credentials in the vault.
 * Each creator returns [] if credentials are missing — no errors thrown.
 */
export async function createAllIntegrationTools(config: IntegrationConfig): Promise<AnyAgentTool[]> {
  const results = await Promise.allSettled(ALL_CREATORS.map(fn => fn(config)));
  const tools: AnyAgentTool[] = [];
  let serviceCount = 0;
  for (const r of results) {
    if (r.status === 'fulfilled' && r.value.length > 0) {
      tools.push(...r.value);
      serviceCount++;
    }
  }
  if (tools.length > 0) console.log(`[integrations] Loaded ${tools.length} tools from ${serviceCount} services`);
  return tools;
}
